### ISSUE TITLE
Module Icons are not displayed correctly in Enterprise Theme

### ISSUE THREAD

**Issue by lisandi** [humhub/humhub-modules-enterprise-theme#22]
The enterprise Theme seems to have a problem with displaying the logo of Modules correctly. We tested on a customer and our own hum hub test account and both have the same issue.

https://community.humhub.com/s/hosting/?contentId=256233&commentId=42044

**Comment by lisandi** [comment]
A solution could be changing the padding to

.container-cards .card .card-header {position: absolute;
     padding: 34px 16px 16px 16px;
     display: table;
     width: 100%;
}

.container-cards .card .card-body {
     flex-grow: 1;
     padding: 100px 16px 24px 16px;
     overflow: auto;
}

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/enterprise-theme/pull/26

@lisandi Sorry, we just forgot to update the theme style when did some changes in core styles. The fix will be in next release, or you can update it manually if run `grunt build-theme --name=enterprise` from your site root folder, or go to folder https://github.com/humhub/enterprise-theme/tree/master/themes/enterprise/less and run `lessc -x build.less ../css/theme.css` as described in the file https://github.com/humhub/enterprise-theme/blob/master/themes/enterprise/less/build.less, but edit the line `@HUMHUB: "/---path-to-humhub-here---/static/less";` to something like this `@HUMHUB: "/../../../../../../static/less";`.
Thanks.

**Comment by luke-** [comment]
@lisandi Fixed with module release 1.8.2

@yurabakhtin Thanks!
